import json	
import re
import os
# -*- coding: utf-8 -*-
def workfile(fil):
	with open(fil,"r+") as f:
		fa = f.read()
	fa = fa.replace("#y","")
	fa = fa.replace("#r","")
	fa = fa.replace("#b","")
	lst=re.findall(r"(\b[\w]+\b)",fa)
	for i in lst:
		d[(i.lower())] = d.get(i.lower(),0) + 1


def trydel(key):
	try:
		d.pop(key)
	except KeyError:
		print(f'Key {key} not found')
filecard="TheClintock-CardStrings.json"
keyw="keywords"
d = {}

print(os.getcwd())
dir=os.getcwd()
for file in os.listdir(dir):
	if file.endswith(".json"):
		workfile(file)

trydel("start")
trydel("1")
trydel("i")
trydel("less")
trydel("now")
trydel("turn")
trydel("turns")
trydel("text")
trydel("it")
trydel("more")
trydel("been")
trydel("end")
trydel("who")
trydel("be")
trydel("per")
trydel("one")
trydel("two")
trydel("three")
trydel("four")
trydel("five")
trydel("six")
trydel("seven")
trydel("eight")
trydel("nine")
trydel("top")
trydel("take")
trydel("takes")
trydel("time")
trydel("times")
trydel("upgrade_description")
trydel("extended_description")
trydel("description")
trydel("nor")
trydel("was")
trydel("and")
trydel("while")
trydel("or")
trydel("this")
trydel("no")
trydel("turn")
trydel("by")
trydel("as")
trydel("2")
trydel("3")
trydel("4")
trydel("5")
trydel("6")
trydel("7")
trydel("8")
trydel("9")
trydel("0")
trydel("you")
trydel("E")
trydel("to")
trydel("at")
trydel("can")
trydel("r")
trydel("m")
trydel("o")
trydel("on")
trydel("will")
trydel("b")
trydel("of")
trydel("x")
trydel("cannot")
trydel("a")
trydel("t")
trydel("a")
trydel("are")
trydel("non")
trydel("new")
trydel("them")
trydel("d")
trydel("nl")
trydel("with")
trydel("spire")
trydel("is")
trydel("they")
trydel("other")
trydel("not")
trydel("any")
trydel("next")
trydel("your")
trydel("the")
trydel("for")
trydel("do")
trydel("does")
trydel("until")
trydel("that")
trydel("same")
trydel("with")
trydel("much")
trydel("in")
trydel("if")
trydel("random")
trydel("when") 	
trydel("an")
trydel("e")
trydel("s")
trydel("name")
trydel("descriptions")
trydel("whenever")
trydel("each")
trydel("times")
trydel("names")
trydel("energy")
trydel("from")
trydel("hit")
trydel("hits")
trydel("then")
trydel("lowest")
trydel("into")
trydel("construct")




with open("kwords","w") as fl:
	for key in d.keys():
		if (d[key] > 4):
			fl.write(key+"\n")
